//HintName: Extensions.g.cs
// <auto-generated />

using System;
using System.Threading.Tasks;

partial class Extensions
{
    public static async Task CallMe(this Task<Subject> ___this, System.AttributeTargets idk = ((System.AttributeTargets)32767))
        => (await ___this).CallMe(idk);
}
