//HintName: Extensions.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading.Tasks;

partial class Extensions
{
    public static async Task CallMe(this Task<Subject> ___this)
        => (await ___this).CallMe();

    public static async Task CallMe(this Task<Subject> ___this, int number)
        => (await ___this).CallMe(number);

    public static async Task<bool> CallMe(this Task<Subject> ___this, int number, string text)
        => (await ___this).CallMe(number, text);
}
